apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: i2styg52o-go-gitops
  description: This is GitOps manifest for i2styg52o-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=i2styg52o-go
    backstage.io/kubernetes-id: i2styg52o-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: i2styg52o-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:i2styg52o-go
